language: python
python:
  - "3.7"
dist: xenial
sudo: true
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE purbeurre;" -U postgres
script:
  - python manage.py migrate
  - python manage.py test
